### PR TITLE
Fix isssuance contract hash calculation 

### LINKED ISSUE #33: issuer_pubkey is missing in IssuanceContract
Reference: https://github.com/vulpemventures/go-elements/pull/183/files

### PR DESCRIPTION
**Pull request by louisinger**
This PR add the `issuer_pubkey` member to the issuance contract and fixes the _contract hash computation_ (`hashContract` function):

1. Stop using `JSON.stringify` and build the JSON string manually instead (it ensures order of members and space between words).
2. reverse the bytes of the contract hash.
3. add `contract_hash.json` fixtures using real contracts from blockstream.info
4. add tests cases to ensure that we compute the same hashes of blockstream.info

@tiero please review

it closes #33

### CODE REVIEW

File: ts_src/issuance.ts [hunk 1]
```diff
@@ -64,7 +65,17 @@ export function hashContract(contract: IssuanceContract): Buffer {
   if (!validateIssuanceContract(contract))
     throw new Error('Invalid asset contract');
 
-  return bcrypto.sha256(Buffer.from(JSON.stringify(contract)));
```
Comment (tiero) [inline ts_src/issuance.ts:67]: what if `JSON.stringify(contract, undefined, 2)`

Comment (tiero) [reply ts_src/issuance.ts:67]: and why not .sort on keys

Comment (louisinger) [reply ts_src/issuance.ts:67]: it works. But the members have to be sorted alphabetically so safer in my opinion to use a string template (Liquid dev website advices to use an external JS lib to stringify the contract but it sounds a bit overkill)

Comment (louisinger) [reply ts_src/issuance.ts:67]: We can't sort the keys using JSON.stringify: the solution is to use https://www.npmjs.com/package/json-stable-stringify
