### PR TITLE
Fix for endianness of contract hash

### LINKED ISSUE #118: Incorrect endianness used for contract hash during issuance
The 'hashContract' function in 'issuance.ts' [reverses the bytes](https://github.com/vulpemventures/liquidjs-lib/blob/v6.0.2-liquid.32/ts_src/issuance.ts#L78) of the contract hash before returning the value. This results in the contract hash remaining in little-endian format when placed within the issuance object returned by the calling function, ['newIssuance'](https://github.com/vulpemventures/liquidjs-lib/blob/v6.0.2-liquid.32/ts_src/issuance.ts#L107). Meanwhile 'newIssuance' is called by the functions ['addInIssuance'](https://github.com/vulpemventures/liquidjs-lib/blob/v6.0.2-liquid.32/ts_src/psetv2/updater.ts#L328) (in psetv2/updater.ts) and ['addIssuance'](https://github.com/vulpemventures/liquidjs-lib/blob/v6.0.2-liquid.32/ts_src/psbt.ts#L335) (in psbt.ts), both of which use the 'assetEntropy' field (where the contact hash is stored) to call ['generateEntropy'](https://github.com/vulpemventures/liquidjs-lib/blob/master/ts_src/issuance.ts#L121). The problem is that the entropy should be generated with the big-endian representation of the contract hash.

The equivalent of this process in Elements can be seen in the [issueasset rpc call](https://github.com/ElementsProject/elements/blob/elements-23.2.1/src/wallet/rpc/elements.cpp#L1388). The contract hash passed as a request parameter in the issueasset function is [parsed using 'ParseHashV'](https://github.com/ElementsProject/elements/blob/elements-23.2.1/src/wallet/rpc/elements.cpp#L1443) which converts the hex of a little-endian contract hash into a big-endian array of bytes. The big-endian array of bytes is then passed into ['GenerateAssetEntropy'](https://github.com/ElementsProject/elements/blob/elements-23.2.1/src/wallet/rpc/elements.cpp#L1473C5-L1473C25), which is the equivalent of the 'generateEntropy' call made by liquidjs and necessarily requires the endianness of the contract hash to be big for the issuance to be recognized by the asset registry.

This issue is related to https://github.com/Blockstream/asset_registry/issues/51 and was found thanks to @Distance71

Edit: Fixed line number for the ParseHashV hyperlink

### PR DESCRIPTION
**Pull request by Randy808**
Fixes #118

### CODE REVIEW

File: ts_src/issuance.ts [hunk 1]
```diff
@@ -72,10 +72,7 @@ export function hashContract(contract: IssuanceContract): Buffer {
     {},
   );
 
-  return bcrypto
-    .sha256(Buffer.from(JSON.stringify(sortedContract)))
-    .slice()
-    .reverse();
+  return bcrypto.sha256(Buffer.from(JSON.stringify(sortedContract))).slice();
```
Comment (louisinger) [inline ts_src/issuance.ts]: could you remove also the `slice()` method ? we used it to reverse the bytes safely but now it's not useful anymore.

**Review by louisinger — CHANGES_REQUESTED** [review]
ACK, nice catch & thanks for the contribution

EDIT: however it seems that blockstream.info is using little endian for the contract hash. I think that's why we originally reversed the bytes while encoded as hex string.

File: test/fixtures/contract_hash.json [hunk 2]
```diff
@@ -10,7 +10,7 @@
       "ticker": "ACE",
       "version": 0
     },
-    "contractHash": "2d9d310ab7885463357382856ec91c7f586b4d2dabfac23849c66aef3d378310"
+    "contractHash": "1083373def6ac64938c2faab2d4d6b587f1cc96e85827335635488b70a319d2d"
```
Comment (louisinger) [inline test/fixtures/contract_hash.json]: looks like blocktream explorer is using little endian encoding: https://blockstream.info/liquid/asset/0c5d451941f37b801d04c46920f2bc5bbd3986e5f56cb56c6b17bedc655e9fc6

now I'm doubting :thinking:

**Comment by Randy808** [comment]
It should display in little-endian, but the hash should be using big-endian when the entropy is calculated.

In issue https://github.com/Blockstream/asset_registry/issues/51, the referenced asset id is `a9d52b02348a097d4f780644064c437e364a41d6299290fef1c49e7d1fbbf665`

This is the code he used to issue the asset: https://github.com/baset-btc/liquid-test/blob/main/test.js

If we look at the asset using [esplora](https://blockstream.info/liquidtestnet/asset/a9d52b02348a097d4f780644064c437e364a41d6299290fef1c49e7d1fbbf665) we'll see the contract_hash is `ed90ec2399bbcca8b38378a1bef6db81127a749ba84b791bacd028183a5faa95`. This is the big-endian value of the contract hash, which can be verified by changing the values of [this script](https://github.com/Randy808/btcplusplusdemo/blob/main/generate_contract_hash.py) (you can delete everything after `contract_hash = hashlib.sha256(contract_json.encode("ascii")).hexdigest()` and just print out the contract_hash). It happens because the little-endian value was used to generate the entropy and esplora is expecting to have to convert it.

In the elements code, [ParseHashV performs length and hex validation](https://github.com/ElementsProject/elements/blob/elements-23.2.1/src/rpc/util.cpp#L105). The string hex is then passed into `uint256S(strHex)`. The [constructor for uint256S](https://github.com/ElementsProject/elements/blob/elements-23.2.1/src/uint256.h#L151) then calls [`SetHex`](https://github.com/ElementsProject/elements/blob/elements-23.2.1//src/uint256.cpp#L65) on a newly initialized uint256. `SetHex` converts the string to a char* and calls another [`SetHex`](https://github.com/ElementsProject/elements/blob/elements-23.2.1//src/uint256.cpp#L37) where the decoding happens. The variable `digits` [is set to the last valid hex character](https://github.com/ElementsProject/elements/blob/elements-23.2.1//src/uint256.cpp#L51) and the digits [are read in reverse order into p1](https://github.com/ElementsProject/elements/blob/elements-23.2.1//src/uint256.cpp#L55-L60) which points to the start of m_data (the data of the uint256)

File: test/fixtures/contract_hash.json (hunk 2 above)
Comment (Randy808) [reply test/fixtures/contract_hash.json]: It should *display* in little-endian, but the hash should be using big-endian when the entropy is calculated.

In issue https://github.com/Blockstream/asset_registry/issues/51, the referenced asset id is a9d52b02348a097d4f780644064c437e364a41d6299290fef1c49e7d1fbbf665

This is the code used to issue the asset in the issue above. It uses liquidjs: https://github.com/baset-btc/liquid-test/blob/main/test.js

If we look at the asset from the issue using [esplora](https://blockstream.info/liquidtestnet/asset/a9d52b02348a097d4f780644064c437e364a41d6299290fef1c49e7d1fbbf665) we'll see the contract_hash is ed90ec2399bbcca8b38378a1bef6db81127a749ba84b791bacd028183a5faa95. This is the big-endian value of the contract hash. This happens because the little-endian value was used to generate the entropy. Esplora was expecting the value used to generate the entropy to be in big-endian and thus reversed the bytes attempting to display it in little-endian (just as it was entered in the elements rpc command), but since the little-endian value was used for entropy generation, this ended up converting little-endian to big-endian instead.

**Sidenote**: To verify the contract data yielded the big-endian value of the contract hash we see on esplora, we can change the values of [this script](https://github.com/Randy808/btcplusplusdemo/blob/main/generate_contract_hash.py), deleting everything after `contract_hash = hashlib.sha256(contract_json.encode("ascii")).hexdigest()` and printing out the value for `contract_hash` (`contract_hash` is the big-endian hex value and `contract_hash_reversed` is the little-endian hex value). 

In the elements code, [ParseHashV performs length and hex validation](https://github.com/ElementsProject/elements/blob/elements-23.2.1/src/rpc/util.cpp#L105). The string hex is then passed into uint256S(strHex). The [constructor for uint256S](https://github.com/ElementsProject/elements/blob/elements-23.2.1/src/uint256.h#L151) then calls [SetHex](https://github.com/ElementsProject/elements/blob/elements-23.2.1//src/uint256.cpp#L65) on a newly initialized uint256. SetHex converts the string to a char* and calls another [SetHex](https://github.com/ElementsProject/elements/blob/elements-23.2.1//src/uint256.cpp#L37) where the decoding happens. The variable `digits` [is set to the last valid hex character](https://github.com/ElementsProject/elements/blob/elements-23.2.1//src/uint256.cpp#L51) and the digits [are read in reverse order into p1](https://github.com/ElementsProject/elements/blob/elements-23.2.1//src/uint256.cpp#L55-L60) which points to the start of m_data (the data of the uint256)

Edit: Rephrased and formatted for clarity

Comment (louisinger) [reply test/fixtures/contract_hash.json]: ok right :+1: 

however, I would revert the changes to the fixtures because they are coming from esplora API (let's keep the string encoded hash reversed). Instead, could you reverse the contractHash in the test file?

Comment (Randy808) [reply test/fixtures/contract_hash.json]: Yeah, will do 👍

**Comment by Randy808** [comment]
Updated

**Review by louisinger — APPROVED** [review]

**Review by altafan — APPROVED** [review]
Thank you @Randy808 for spotting this out and providing a fix for it.
